# Generated by Django 6.1.1 on 2026-09-11 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_domicilio', models.CharField(choices=[('DUPLEX', 'Dúplex'), ('FLAT', 'Flat'), ('CASA', 'Casa')], default='FLAT', max_length=10)),
                ('numero_domicilio', models.CharField(max_length=20, unique=True, verbose_name='N° Departamento')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('dni', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo dígitos.')], verbose_name='DNI')),
                ('celular', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo dígitos.')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('cochera_monto', models.DecimalField(decimal_places=2, default=0, help_text='0 si no tiene cochera.', max_digits=10, verbose_name='Cobro de cochera')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['numero_domicilio'],
            },
        ),
        migrations.CreateModel(
            name='GastoEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Mes (día 1)')),
                ('descripcion', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('GENERAL', 'Mantenimiento (servicios generales)'), ('AGUA_COMUN', 'Agua de área común')], default='GENERAL', max_length=12)),
            ],
            options={
                'verbose_name': 'Gasto del edificio',
                'verbose_name_plural': 'Gastos del edificio',
                'ordering': ['-periodo', 'categoria', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TarifaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('consumo_limite', models.DecimalField(blank=True, decimal_places=2, help_text='Tope superior del tramo. Vacío = sin tope.', max_digits=8, null=True, verbose_name='Consumo límite (m³)')),
                ('tarifa', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Tarifa por m³')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa de agua',
                'verbose_name_plural': 'Tarifas de agua',
                'ordering': ['consumo_limite'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Mes (día 1)')),
                ('fecha_vencimiento', models.DateField()),
                ('m3_consumidos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_agua', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_area_comun', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_cochera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gastos_adicionales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-periodo', 'departamento'],
                'unique_together': {('departamento', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('metodo', models.CharField(blank=True, max_length=50)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='departamentos.recibo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='LecturaMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Mes (día 1)')),
                ('lectura_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Lectura de medidor',
                'verbose_name_plural': 'Lecturas de medidor',
                'ordering': ['-periodo', 'departamento'],
                'unique_together': {('departamento', 'periodo')},
            },
        ),
    ]
