# Generated by Django 6.1.1 on 2026-09-19 23:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.PositiveIntegerField(default=100)),
                ('es_recurrente', models.BooleanField(default=False, verbose_name='Se genera cada mes')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de deuda',
                'verbose_name_plural': 'Conceptos de deuda',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_domicilio', models.CharField(choices=[('DUPLEX', 'Dúplex'), ('FLAT', 'Flat'), ('CASA', 'Casa')], default='FLAT', max_length=10)),
                ('numero_domicilio', models.CharField(max_length=20, unique=True, verbose_name='N° Departamento')),
                ('nombres', models.CharField(blank=True, max_length=100, verbose_name='Nombres del propietario')),
                ('apellidos', models.CharField(blank=True, max_length=100, verbose_name='Apellidos del propietario')),
                ('dni', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo dígitos.')], verbose_name='DNI')),
                ('celular', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo dígitos.')], verbose_name='Celular del propietario')),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('tiene_inquilino', models.BooleanField(default=False, verbose_name='¿Tiene inquilino?')),
                ('celular_inquilino', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo dígitos.')], verbose_name='Celular del inquilino')),
                ('cochera_monto', models.DecimalField(decimal_places=2, default=0, help_text='0 si no tiene cochera.', max_digits=10, verbose_name='Cobro de cochera')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['numero_domicilio'],
            },
        ),
        migrations.CreateModel(
            name='GastoEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Mes (día 1)')),
                ('descripcion', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('GENERAL', 'Mantenimiento (servicios generales)'), ('AGUA_COMUN', 'Agua de área común')], default='GENERAL', max_length=12)),
                ('compartido', models.BooleanField(default=True, help_text='Marcado: el monto se divide entre los deptos. Desmarcado: cada depto paga el monto completo.', verbose_name='Compartido (dividir entre todos)')),
            ],
            options={
                'verbose_name': 'Gasto adicional del mes',
                'verbose_name_plural': 'Gastos adicionales del mes',
                'ordering': ['-periodo', 'categoria', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('GENERAL', 'Mantenimiento (servicios generales)'), ('AGUA_COMUN', 'Agua de área común')], default='GENERAL', max_length=12)),
                ('compartido', models.BooleanField(default=False, help_text='Desmarcado: cada depto paga el monto completo. Marcado: el monto se divide entre los deptos.', verbose_name='Compartido (dividir entre todos)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gasto fijo',
                'verbose_name_plural': 'Gastos fijos',
                'ordering': ['categoria', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rol', models.CharField(blank=True, help_text='Ej: Gasfitero, Seguridad, Limpieza, Cámaras, Bombas...', max_length=80, verbose_name='Rol / servicio')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Ingrese solo dígitos.')])),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarifaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('consumo_limite', models.DecimalField(blank=True, decimal_places=2, help_text='Tope superior del tramo. Vacío = sin tope.', max_digits=8, null=True, verbose_name='Consumo límite (m³)')),
                ('tarifa', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Tarifa por m³')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa de agua',
                'verbose_name_plural': 'Tarifas de agua',
                'ordering': ['consumo_limite'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Mes (día 1)')),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='departamentos.concepto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['periodo', 'concepto'],
                'unique_together': {('departamento', 'concepto', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('metodo', models.CharField(blank=True, max_length=50)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('concepto', models.ForeignKey(blank=True, help_text='Vacío = pago general (cancela lo más antiguo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='departamentos.concepto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Imputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='departamentos.cargo')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='departamentos.pago')),
            ],
            options={
                'verbose_name': 'Imputación de pago',
                'verbose_name_plural': 'Imputaciones de pago',
            },
        ),
        migrations.CreateModel(
            name='LecturaMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Mes (día 1)')),
                ('lectura_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Lectura de medidor',
                'verbose_name_plural': 'Lecturas de medidor',
                'ordering': ['-periodo', 'departamento'],
                'unique_together': {('departamento', 'periodo')},
            },
        ),
    ]
