# Generated by Django 6.1.1 on 2026-09-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoedificio',
            name='departamentos',
            field=models.ManyToManyField(blank=True, help_text='Personalizado: aplica solo a estos deptos. Vacío = a todos.', related_name='gastos_dirigidos', to='departamentos.departamento'),
        ),
    ]
