# Generated by Django 6.1.1 on 2026-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('GENERAL', 'Mantenimiento (servicios generales)'), ('AGUA_COMUN', 'Agua de área común')], default='GENERAL', max_length=12)),
                ('compartido', models.BooleanField(default=False, help_text='Desmarcado: cada depto paga el monto completo. Marcado: el monto se divide entre los deptos.', verbose_name='Compartido (dividir entre todos)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gasto fijo',
                'verbose_name_plural': 'Gastos fijos',
                'ordering': ['categoria', 'descripcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='gastoedificio',
            options={'ordering': ['-periodo', 'categoria', 'descripcion'], 'verbose_name': 'Gasto adicional del mes', 'verbose_name_plural': 'Gastos adicionales del mes'},
        ),
        migrations.AddField(
            model_name='gastoedificio',
            name='compartido',
            field=models.BooleanField(default=True, help_text='Marcado: el monto se divide entre los deptos. Desmarcado: cada depto paga el monto completo.', verbose_name='Compartido (dividir entre todos)'),
        ),
    ]
